# Generated by Django 2.0.1 on 2018-02-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_userprofile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='password',
            field=models.CharField(help_text="<a href='password/'>Change Password</a>", max_length=128, verbose_name='password'),
        ),
    ]
