# Generated by Django 2.0.1 on 2018-02-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_userprofile_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_num',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
