# Generated by Django 2.0.1 on 2018-02-14 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20180212_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stu_account',
            field=models.ForeignKey(blank=True, help_text='Create this account only after the customer has enrolled in successfully', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Customer'),
        ),
    ]
