# Generated by Django 2.0.1 on 2018-02-15 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_userprofile_stu_account'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [['permission_test', 'Hello permissions']]},
        ),
    ]
